### ISSUE TITLE
Error log on latest MIUI 6 (5.4.10 for now)

### ISSUE THREAD

**Issue by What-Zit-Tooya** [CodeingBoy/RemoveStatusBar#1]
I use WSM Tools v2.3.5 . I get this error log:

java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
    at me.CodeingBoy.RemoveSimpleStatusbar.Functions$1.handleLayoutInflated(Functions.java:24)
    at de.robv.android.xposed.callbacks.XC_LayoutInflated.call(XC_LayoutInflated.java:33)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at android.content.res.XResources$3.afterHookedMethod(XResources.java:224)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:652)
    at android.view.LayoutInflater.parseInclude(Native Method)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:842)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:638)
    at android.view.LayoutInflater.parseInclude(Native Method)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:638)
    at android.view.LayoutInflater.inflate(Native Method)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
    at android.view.View.inflate(View.java:17831)
    at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:796)
    at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3553)
    at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3528)
    at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:256)
    at com.android.systemui.statusbar.phone.PhoneStatusBar.bindViews(PhoneStatusBar.java:717)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:638)
    at com.android.systemui.statusbar.phone.PhoneStatusBar.bindViews(Native Method)
    at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:664)
    at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:53)
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2770)
    at android.app.ActivityThread.access$1800(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5333)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:136)
    at dalvik.system.NativeStart.main(Native Method)

Also i get this error log if i activate MiSecondClock:

java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.Clock#b()#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:196)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:146)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:153)
    at me.CodeingBoy.MiSeconds.Modifications.handleLoadPackage(Modifications.java:34)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$3.afterHookedMethod(XposedBridge.java:256)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:652)
    at android.app.LoadedApk.<init>(Native Method)
    at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1811)
    at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1774)
    at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1747)
    at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2006)
    at android.app.ContextImpl.createPackageContext(ContextImpl.java:1992)
    at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:637)
    at android.app.ActivityThread.installProvider(ActivityThread.java:5022)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4623)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4563)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:638)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1500(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5333)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:136)
    at dalvik.system.NativeStart.main(Native Method)

Will you fix them?

**Comment by CodeingBoy** [comment]
Got it. I will look into it.

**Comment by CodeingBoy** [comment]
Sorry for your Waiting.But in 5.6.4 it works all fine.Try updating your MIUI.

**Comment by What-Zit-Tooya** [comment]
Thank you... working fine now. Case solved bro. :)
Btw can you update / mod MiThemes in order to support miui 6? Because the dev had abandoned it.
Here's source code for it https://github.com/BurgerZ/WSM-Project/tree/master/Modules/MiThemes

**Comment by CodeingBoy** [comment]
I will give it a try, but I think it is too difficult for me.And there is a legal risk because I'm living in China.

**Comment by What-Zit-Tooya** [comment]
I know about it.. but now miui has been release globally. Some of them use china rom & can not buy theme using micredit like me. Because of country restriction. 
To bypass it, use 3rd party rom with cr@cked thememanager is one of solutions.
